// fetch data
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_LABELS = 'FETCH_LABELS';
export const LOADING_FINISHED = 'LOADING_FINISHED';

// Label CRUD
export const CREATE_LABEL = 'CREATE_LABEL';
export const MODIFY_LABEL = 'MODIFY_LABEL';
export const MODIFY_LABEL_SELECTION = 'MODIFY_LABEL_SELECTION';
export const SELECT_ALL_LABELS = 'SELECT_ALL_LABELS';
export const DESELECT_ALL_LABELS = 'DESELECT_ALL_LABELS';

// TrackList filtering
export const TRACKS_SEARCH = 'TRACKS_SEARCH';

// TrackSlide selection
export const MODIFY_TRACK_SELECTION = 'MODIFY_TRACK_SELECTION';
export const SELECT_ALL_TRACKS = 'SELECT_ALL_TRACKS';
export const DESELECT_ALL_TRACKS = 'DESELECT_ALL_TRACKS';

// Track-Label diff state
export const SET_LABEL_CHANGES = 'SET_LABEL_CHANGES';
export const CLEAR_LABEL_CHANGES = 'CLEAR_LABEL_CHANGES';

// Track Objects
export const UPDATE_TRACKS_LABELS = 'UPDATE_TRACKS_LABELS';

// Filter
export const MODIFY_PLAYLIST_FILTER = 'MODIFY_PLAYLIST_FILTER';
export const FILTER_BY_PLAYLIST = 'FILTER_BY_PLAYLIST';
export const MODIFY_LABEL_FILTER = 'MODIFY_LABEL_FILTER';
export const FILTER_BY_LABEL = 'FILTER_BY_LABEL';