// Initial Loading
export const LOADING_FINISHED = 'LOADING_FINISHED';
export const LOADING_STARTED = 'LOADING_STARTED';
export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_LABELS = 'FETCH_LABELS';

// Label CRUD
export const CREATE_LABEL = 'CREATE_LABEL';
export const MODIFY_LABEL = 'MODIFY_LABEL';
export const MODIFY_LABEL_SELECTION = 'MODIFY_LABEL_SELECTION';
export const SELECT_ALL_LABELS = 'SELECT_ALL_LABELS';
export const DESELECT_ALL_LABELS = 'DESELECT_ALL_LABELS';

// Playlist Selection
export const MODIFY_PLAYLIST_SELECTION = 'MODIFY_PLAYLIST_SELECTION';

// TrackSlide selection
export const MODIFY_TRACK_SELECTION = 'MODIFY_TRACK_SELECTION';
export const SELECT_ALL_TRACKS = 'SELECT_ALL_TRACKS';
export const DESELECT_ALL_TRACKS = 'DESELECT_ALL_TRACKS';

// Track-Label diff state
export const SET_LABEL_CHANGES = 'SET_LABEL_CHANGES';
export const CLEAR_LABEL_CHANGES = 'CLEAR_LABEL_CHANGES';
// Playlist-Track diff state
export const SET_TRACK_CHANGES = 'SET_TRACK_CHANGES';

// Track Objects
export const UPDATE_TRACKS_LABELS = 'UPDATE_TRACKS_LABELS';
export const UPDATE_TRACKS_PLAYLISTS = 'UPDATE_TRACKS_PLAYLISTS';

// Filter Selection
export const MODIFY_PLAYLIST_FILTER = 'MODIFY_PLAYLIST_FILTER';
export const SELECT_ALL_PLAYLIST_FILTERS = 'SELECT_ALL_PLAYLIST_FILTERS';
export const DESELECT_ALL_PLAYLIST_FILTERS = 'DESELECT_ALL_PLAYLIST_FILTERS';
export const MODIFY_LABEL_FILTER = 'MODIFY_LABEL_FILTER';
export const DESELECT_ALL_LABEL_FILTERS = 'DESELECT_ALL_LABEL_FILTERS';
export const MODIFY_SEARCH_FILTER = 'MODIFY_SEARCH_FILTER';
export const REMOVE_SEARCH_FILTER = 'REMOVE_SEARCH_FILTER';
// Filter Tracks
export const FILTER_BY_PLAYLIST = 'FILTER_BY_PLAYLIST';
export const FILTER_BY_LABEL = 'FILTER_BY_LABEL';
export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH';

// Playlist Management
export const MODIFY_PLAYLIST_FIELD = 'MODIFY_PLAYLIST_FIELD';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';